name: Deploy static Next.js to GitHub Pages

on:
  push:
    branches: [main] # rebuild every push to main
  workflow_dispatch: # manual “Run workflow” button

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build # creates .next/
      - run: npx next export # writes static site to ./out
      - run: echo "" > out/.nojekyll # keep _next/ etc.

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # upload the export folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/deploy-pages@v4
